"""PROTOTYPE - delete after Phase 2 ADR-001 lands.

Static-analyzes every JSON in workflows/ and writes a Markdown report
of node class_types, logical-role guesses, and required custom-node packs.

This is what we use to design the v3 workflow manifest format
when live ComfyUI is unreachable.

    python scripts/analyze_workflows.py [--out docs/v3/workflows-static.md]
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

# class_type prefix -> guessed custom node pack (best-effort heuristic).
# Stock ComfyUI is "comfyui-core". Anything else is a third-party pack.
PACK_HINTS: list[tuple[str, str]] = [
    ("DyPE_FLUX", "ComfyUI-DyPE"),
    ("PathchSageAttentionKJ", "ComfyUI-KJNodes (sage-attention patch)"),
    ("PatchSageAttentionKJ", "ComfyUI-KJNodes"),
    ("KJ", "ComfyUI-KJNodes"),
    ("RIFE", "ComfyUI-Frame-Interpolation"),
    ("VHS_", "ComfyUI-VideoHelperSuite"),
    ("WanI2V", "ComfyUI-Wan"),
    ("Wan", "ComfyUI-Wan"),
    ("HiDream", "ComfyUI-HiDream"),
    ("Qwen", "ComfyUI-Qwen / Qwen-Image-Edit"),
    ("Florence", "ComfyUI-Florence2"),
    ("F5TTS", "ComfyUI-F5-TTS"),
    ("ChatterboxTTS", "ComfyUI-Chatterbox"),
    ("ACE_Step", "ComfyUI-ACE-Step"),
    ("StableAudio", "ComfyUI-StableAudio"),
    ("UltimateSDUpscale", "ComfyUI-UltimateSDUpscale"),
    ("RealESRGAN", "ComfyUI-RealESRGAN / Impact"),
]

# Logical role guesser: best class_type -> role mapping.
ROLE_HINTS: dict[str, str] = {
    "CLIPTextEncode": "prompt_text",
    "EmptyLatentImage": "latent_size",
    "EmptySD3LatentImage": "latent_size",
    "KSampler": "sampler",
    "KSamplerSelect": "sampler_name",
    "SamplerCustomAdvanced": "sampler",
    "BasicScheduler": "scheduler",
    "RandomNoise": "seed",
    "LoraLoader": "lora",
    "LoraLoaderModelOnly": "lora",
    "VAEDecode": "vae_decode",
    "VAEDecodeTiled": "vae_decode",
    "VAELoader": "vae",
    "UNETLoader": "model",
    "CheckpointLoaderSimple": "model",
    "DualCLIPLoader": "clip",
    "SaveImage": "output_image",
    "VHS_VideoCombine": "output_video",
    "DyPE_FLUX": "dype_params",
    "ConditioningZeroOut": "negative",
}


def pack_for(class_type: str) -> str:
    for prefix, pack in PACK_HINTS:
        if class_type.startswith(prefix) or prefix.lower() in class_type.lower():
            return pack
    return "comfyui-core"


def analyze_workflow(path: Path) -> dict:
    data = json.loads(path.read_text())
    nodes_by_id: dict[str, dict] = {}
    class_types: dict[str, list[str]] = defaultdict(list)
    roles: dict[str, list[str]] = defaultdict(list)
    packs: set[str] = set()
    for node_id, node in data.items():
        if not isinstance(node, dict):
            continue
        ct = node.get("class_type", "?")
        nodes_by_id[node_id] = node
        class_types[ct].append(node_id)
        if ct in ROLE_HINTS:
            roles[ROLE_HINTS[ct]].append(node_id)
        elif ct == "CLIPTextEncode":
            title = (node.get("_meta") or {}).get("title", "").lower()
            role = "prompt_negative" if "negative" in title else "prompt_positive"
            roles[role].append(node_id)
        packs.add(pack_for(ct))
    if "CLIPTextEncode" in class_types:
        positives = []
        negatives = []
        for node_id in class_types["CLIPTextEncode"]:
            title = (nodes_by_id[node_id].get("_meta") or {}).get("title", "").lower()
            if "negative" in title or "neg" in title:
                negatives.append(node_id)
            else:
                positives.append(node_id)
        if positives:
            roles["prompt_positive"] = positives
        if negatives:
            roles["prompt_negative"] = negatives
    return {
        "file": path.name,
        "node_count": len(nodes_by_id),
        "class_types": dict(class_types),
        "roles": dict(roles),
        "packs": sorted(packs),
    }


def render(reports: list[dict]) -> str:
    lines = [
        "# DisComfy v3 - Static Workflow Analysis",
        "",
        f"Generated by `scripts/analyze_workflows.py` against {len(reports)} workflows.",
        "",
        "Heuristic only. Confirm against live `/object_info` once ComfyUI is reachable.",
        "",
        "## Required custom node packs (union across all workflows)",
        "",
    ]
    all_packs: dict[str, set[str]] = defaultdict(set)
    for r in reports:
        for p in r["packs"]:
            all_packs[p].add(r["file"])
    lines += ["| pack | used by |", "| --- | --- |"]
    for pack, files in sorted(all_packs.items()):
        lines.append(f"| `{pack}` | {', '.join(sorted(files))} |")
    lines.append("")

    lines += ["## Per-workflow breakdown", ""]
    for r in reports:
        lines.append(f"### `{r['file']}` ({r['node_count']} nodes)")
        lines.append("")
        lines.append("**Roles (logical role -> node id(s)):**")
        lines.append("")
        for role, ids in sorted(r["roles"].items()):
            lines.append(f"- `{role}`: {', '.join(ids)}")
        lines.append("")
        lines.append("**class_types used:**")
        lines.append("")
        for ct, ids in sorted(r["class_types"].items()):
            pack = pack_for(ct)
            lines.append(f"- `{ct}` x{len(ids)} (pack: `{pack}`)")
        lines.append("")
        lines.append("**Required packs:** " + ", ".join(f"`{p}`" for p in r["packs"]))
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workflows", default="workflows", help="workflow directory")
    parser.add_argument("--out", default="docs/v3/workflows-static.md", help="output markdown")
    args = parser.parse_args()

    wf_dir = Path(args.workflows)
    reports = [analyze_workflow(p) for p in sorted(wf_dir.glob("*.json"))]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(reports))
    print(f"[analyze] wrote {out} ({len(reports)} workflows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
